# Generated by Django 5.2.3 on 2025-07-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_approval_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskRequest',
        ),
    ]
