# Generated by Django 5.0.6 on 2025-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_chatmessage_chatattachment_chatnotification_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
