# Generated by Django 5.0.6 on 2025-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_chatmessage_id_alter_chatroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
