# Generated by Django 5.2.3 on 2025-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_chatroom_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
